// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WLCProgressions.Data;

#nullable disable

namespace WLCProgressions.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220502225131_Add No Progression Route table2")]
    partial class AddNoProgressionRoutetable2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WLCProgressions.Models.ChartData", b =>
                {
                    b.Property<int>("ChartDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChartDataID"), 1L, 1);

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ChartTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CollegeCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CollegeName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CourseCode")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("CourseTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FacCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FacName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("TeamCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("TeamName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ChartDataID");

                    b.ToTable("ChartData");
                });

            modelBuilder.Entity("WLCProgressions.Models.Config", b =>
                {
                    b.Property<string>("AcademicYear")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ProgressionYear")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("AcademicYear");

                    b.ToView("Config", "dbo");
                });

            modelBuilder.Entity("WLCProgressions.Models.CourseGroup", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("AimCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("AimTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CompletedRecords")
                        .HasColumnType("int");

                    b.Property<double>("CompletedRecordsPer")
                        .HasColumnType("float");

                    b.Property<string>("CourseCode")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("CourseTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Enrolments")
                        .HasColumnType("int");

                    b.Property<string>("FacCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FacName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HasDestination")
                        .HasColumnType("int");

                    b.Property<int>("HasProgression")
                        .HasColumnType("int");

                    b.Property<int>("HasProgressionDestination")
                        .HasColumnType("int");

                    b.Property<int>("HasValidDestination")
                        .HasColumnType("int");

                    b.Property<int>("OutstandingRecords")
                        .HasColumnType("int");

                    b.Property<double>("OutstandingRecordsPer")
                        .HasColumnType("float");

                    b.Property<string>("SiteCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SiteName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TeamCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("TeamName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CourseID", "GroupID");

                    b.ToView("CourseGroup", "dbo");
                });

            modelBuilder.Entity("WLCProgressions.Models.NoProgressionRoute", b =>
                {
                    b.Property<string>("StudentRef")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("OfferingID")
                        .HasColumnType("int");

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfferingGroupID")
                        .HasColumnType("int");

                    b.Property<string>("SystemDatabase")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentRef", "OfferingID");

                    b.ToTable("PRG_NoProgressionRoute");
                });

            modelBuilder.Entity("WLCProgressions.Models.Progression", b =>
                {
                    b.Property<string>("StudentRef")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("CourseFromID")
                        .HasColumnType("int");

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("CourseToID")
                        .HasColumnType("int");

                    b.Property<int?>("GroupFromID")
                        .HasColumnType("int");

                    b.Property<int?>("GroupToID")
                        .HasColumnType("int");

                    b.Property<int?>("OfferConditionID")
                        .HasColumnType("int");

                    b.Property<int>("OfferTypeID")
                        .HasColumnType("int");

                    b.Property<string>("ProgressionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadyToEnrolOption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemDatabase")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentRef", "CourseFromID");

                    b.ToView("Progression", "dbo");
                });

            modelBuilder.Entity("WLCProgressions.Models.SelectListData", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Code");

                    b.ToView("SelectListData", "dbo");
                });

            modelBuilder.Entity("WLCProgressions.Models.StaffMember", b =>
                {
                    b.Property<string>("StaffRef")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Forename")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StaffDetails")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StaffRef");

                    b.ToView("StaffMember", "dbo");
                });

            modelBuilder.Entity("WLCProgressions.Models.Student", b =>
                {
                    b.Property<string>("StudentRef")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Age31stAug")
                        .HasColumnType("int");

                    b.Property<string>("AppliedCoursesNextYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AttendPer")
                        .HasColumnType("float");

                    b.Property<int>("ClassesAbsent")
                        .HasColumnType("int");

                    b.Property<int>("ClassesAuthAbsence")
                        .HasColumnType("int");

                    b.Property<int>("ClassesCounted")
                        .HasColumnType("int");

                    b.Property<int>("ClassesCourses")
                        .HasColumnType("int");

                    b.Property<int>("ClassesLate")
                        .HasColumnType("int");

                    b.Property<int>("ClassesMarked")
                        .HasColumnType("int");

                    b.Property<int>("ClassesNeutral")
                        .HasColumnType("int");

                    b.Property<int>("ClassesPlanned")
                        .HasColumnType("int");

                    b.Property<int>("ClassesPresent")
                        .HasColumnType("int");

                    b.Property<int>("ClassesUnmarked")
                        .HasColumnType("int");

                    b.Property<string>("CollegeCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CollegeName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CompletionStatusCode")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CompletionStatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseCode")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("CourseTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DestinationChanged")
                        .HasColumnType("bit");

                    b.Property<int?>("DestinationCode")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationIsActual")
                        .HasColumnType("int");

                    b.Property<string>("DestinationName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EnrolledCoursesNextYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FacName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Forename")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasAlreadyApplied")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadyToEnrol")
                        .HasColumnType("bit");

                    b.Property<int>("NumAppsNextYear")
                        .HasColumnType("int");

                    b.Property<int>("NumEnrolsNextYear")
                        .HasColumnType("int");

                    b.Property<int>("OfferCondition")
                        .HasColumnType("int");

                    b.Property<int>("OfferType")
                        .HasColumnType("int");

                    b.Property<string>("OnTrackToAchieveCode")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("OnTrackToAchieveColour")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OnTrackToAchieveTerm")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ProgressLearner")
                        .HasColumnType("bit");

                    b.Property<string>("ReadyToEnrolOption")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RiskCode")
                        .HasColumnType("int");

                    b.Property<string>("RiskColour")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RiskName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SiteCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SiteName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SystemDatabase")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TeamCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("TeamName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("StudentRef");

                    b.ToView("Student", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
